apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "mnist-sample"
spec:
  default:
    predictor:
      tensorflow:
        storageUri: "pvc://your-dataset/mnist/export"
