apiVersion: batch/v1
kind: Job
metadata:
  name: generate-keys
spec:
  template:
    spec:
      serviceAccountName: dataset-operator
      containers:
        - name: generate-keys
          image: ${GENERAGE_KEYS_IMAGE}
          imagePullPolicy: Always
          env:
            - name: DATASET_OPERATOR_NAMESPACE
              value: ${DATASET_OPERATOR_NAMESPACE}
      restartPolicy: Never
  backoffLimit: 4