---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_DB: hive_metastore 
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: sekritpasswd
