---
apiVersion: v1
kind: Service
metadata:
  name: metastoredb
spec:
  type: "LoadBalancer"
  ports:
    - port: 5432
  selector:
    app: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  serviceName: "metastore-db"
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgres
          image: postgres:10
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
  volumeClaimTemplates:
  - metadata:
      name: postgresdb
    spec:
      accessModes: 
      - ReadWriteOnce 
      resources:
        requests:
          storage: 5Gi
      selector:
        matchLabels:
          type: local
