---
apiVersion: v1
kind: Pod
metadata:
  name: sampleapp
  namespace: default
  labels:
    dataset.0.id: "bookds"
    dataset.0.useas: "mount"
spec:
  containers:
    - name: nginx
      image: nginx
