name: document
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - run: python -m pip install --upgrade pipenv wheel
      - run: pipenv update
      - uses: actions/checkout@v3
        with:
           ref: gh-pages
           path: pages
      - run: |
           cp -v pages/index.yaml docs/
      - run: pipenv run mkdocs gh-deploy --force
